{
 "title": "Guava Cache",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cache", "label": "Cache", "query": { "query": "label_values(cache)" } }
  ]
 },
 "panels": [
  {
   "title": "Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(cache_gets_total{cache=\"$cache\", result=\"hit\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(cache_gets_total{cache=\"$cache\", result=\"miss\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_size{cache=\"$cache\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(cache_evictions_total{cache=\"$cache\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The time the cache has spent loading new values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(cache_load_duration_seconds{cache=\"$cache\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}